# Generated by Django 5.0.3 on 2024-04-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follows_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follows',
            new_name='Follow',
        ),
    ]
