# Generated by Django 5.0.3 on 2024-04-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_follows_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='userID',
            new_name='user',
        ),
    ]
