# Generated by Django 5.0.3 on 2024-03-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='imageURL',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='startBid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
