# Generated by Django 5.0.3 on 2024-03-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_imageurl_listing_startbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Animals', 'Animals'), ('Wands', 'Wands'), ('Potions', 'Potions'), ('Consumables', 'Consumables'), ('Misc', 'Misc')], default='Misc', max_length=50),
        ),
    ]
