# Generated by Django 5.0.3 on 2024-03-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='username',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='reserve',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='startBid',
            field=models.FloatField(default=0),
        ),
    ]
