# Generated by Django 5.0.3 on 2024-03-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_username_listing_owner_alter_bid_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageURL',
            field=models.URLField(null=True),
        ),
    ]
