# Generated by Django 5.0.3 on 2024-03-25 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_listing_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watches',
            field=models.ManyToManyField(blank=True, related_name='watched', to=settings.AUTH_USER_MODEL),
        ),
    ]
