# Generated by Django 5.0.3 on 2024-04-03 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_watches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='value',
            new_name='bid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bidID',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='listingID',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='time',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='startBid',
        ),
        migrations.AddField(
            model_name='bid',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.bid'),
        ),
    ]
