# Generated by Django 5.0.3 on 2024-05-15 19:52

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0002_user_dob_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=75)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.CreateModel(
            name='Campsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=300)),
                ('picture', models.URLField(blank=True, null=True)),
                ('address1', models.CharField(max_length=75)),
                ('address2', models.CharField(max_length=75)),
                ('town', models.CharField(max_length=75)),
                ('county', models.CharField(max_length=75)),
                ('postcode', models.CharField(max_length=75)),
                ('gps', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('facilities', models.ManyToManyField(blank=True, related_name='facilities', to='camping.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Tent', 'Tent'), ('Campervan', 'Campervan'), ('Caravan', 'Caravan'), ('Motorhome', 'Motorhome'), ('Glamping', 'Glamping')], default='Tent', max_length=10)),
                ('power', models.BooleanField()),
                ('capacity', models.PositiveBigIntegerField(default=1)),
                ('length', models.PositiveBigIntegerField(default=1)),
                ('width', models.PositiveBigIntegerField(default=1)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='camping.campsite')),
            ],
        ),
    ]
