# Generated by Django 5.0.3 on 2024-05-15 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0003_facility_alter_user_phone_campsite_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsite',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
