# Generated by Django 5.0.3 on 2024-05-23 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0004_campsite_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plot',
            old_name='site',
            new_name='campsite',
        ),
        migrations.AddField(
            model_name='plot',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='campsite',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateField()),
                ('checkout', models.DateField()),
                ('notes', models.CharField(max_length=300)),
                ('cost', models.PositiveIntegerField(default=1)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_plot', to='camping.plot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
