# Generated by Django 5.0.3 on 2024-05-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0005_rename_site_plot_campsite_plot_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='details',
        ),
    ]
