# Generated by Django 5.0.3 on 2024-05-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0006_remove_facility_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='facility',
            new_name='name',
        ),
    ]
