# Generated by Django 5.0.3 on 2024-06-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0007_rename_facility_facility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='name',
            field=models.CharField(default='Plot', max_length=75),
            preserve_default=False,
        ),
    ]
