# Generated by Django 5.0.3 on 2024-06-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0008_plot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='people',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
