# Generated by Django 5.0.3 on 2024-07-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0009_booking_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campsite',
            name='gps',
        ),
        migrations.AddField(
            model_name='campsite',
            name='latitude',
            field=models.CharField(default=51.4543, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campsite',
            name='longitude',
            field=models.CharField(default=-2.6018, max_length=25),
            preserve_default=False,
        ),
    ]
