# Generated by Django 5.0.3 on 2024-08-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0010_remove_campsite_gps_campsite_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campsite',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='campsite',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
